### ISSUE TITLE
t.Editor.Tools.blockTools[o] is not a constructor

### ISSUE THREAD

**Issue by mykhailo-monchak** [trinhtam/editorjs-hyperlink#1]
Hi there,

Thank you for the great idea!

Unfortunately, I'm not able to enable it.

The error in the browser console is:
`react_devtools_backend.js:2450 Paste handling for «hyperlink» Tool hasn't been set up because of the error TypeError: t.Editor.Tools.blockTools[o] is not a constructor
    at t.processTool (editor.js:2)
    at Array.forEach (<anonymous>)
    at w.value (editor.js:2)
    at w.<anonymous> (editor.js:2)
    at c (editor.js:2)
    at Generator._invoke (editor.js:2)
    at Generator.t.<computed> [as next] (editor.js:2)
    at n (editor.js:2)
    at s (editor.js:2)
    at editor.js:2
    at new Promise (<anonymous>)
    at w.<anonymous> (editor.js:2)
    at w.value (editor.js:2)
    at editor.js:2
    at c (editor.js:2)
    at Generator._invoke (editor.js:2)
    at Generator.t.<computed> [as next] (editor.js:2)
    at n (editor.js:2)
    at s (editor.js:2)
    at editor.js:2
    at new Promise (<anonymous>)
    at editor.js:2`

The tools config is:
`
import Download from './editorjs_plugins/download/download.js';
import './editorjs_plugins/download/download.css';
import { ToolConstructable, ToolSettings } from '@editorjs/editorjs';

const Table = require('@editorjs/table');
const List = require('@editorjs/list');
const Code = require('@editorjs/code');
const Raw = require('@editorjs/raw');
const Header = require('@editorjs/header');
const Image = require('@editorjs/image');
const Paragraph = require('@editorjs/paragraph');
const Marker = require('@editorjs/marker');
const CheckList = require('@editorjs/checklist');
const Delimiter = require('@editorjs/delimiter');
const InlineCode = require('@editorjs/inline-code');
const Hyperlink = require('editorjs-hyperlink');

export const EDITOR_JS_TOOLS: { [toolName: string]: ToolConstructable | ToolSettings } = {
  //   embed: Embed,
  table: { class: Table, inlineToolbar: true },
  paragraph: { class: Paragraph, config: { preserveBlank: true }, inlineToolbar: true },
  list: { class: List, inlineToolbar: true },
  //   warning: Warning,
  code: { class: Code },
  //   linkTool: LinkTool,
  image: {
    class: Image,
    inlineToolbar: true,
    config: {
      uploader: {
        // the stub functions are required here in order to be able to override them later
        uploadByFile(file: File): Promise<{ success: 1 | 0; file: { url: string } }> {
          return null as any;
        },
        uploadByUrl(url: string): Promise<{ success: 1 | 0; file: { url: string } }> {
          return null as any;
        },
      },
    },
  },
  raw: { class: Raw },
  header: { class: Header, inlineToolbar: true },
  //   quote: Quote,
  marker: { class: Marker },
  checklist: { class: CheckList, inlineToolbar: true },
  delimiter: { class: Delimiter },
  inlineCode: { class: InlineCode },
  download: Download as any,
  hyperlink: {
    class: Hyperlink,
    config: {
      shortcut: 'CMD+L',
    },
  },
};
`

Please help.

**Comment by trinhtam** [comment]
Please update new version editorjs-hyperlink
`editorjs-hyperlink@1.0.1`

**Comment by mykhailo-monchak** [comment]
Perfect! Thank you for a great job!
