### ISSUE TITLE
feature request: default target value

### ISSUE THREAD

**Issue by mykhailo-monchak** [trinhtam/editorjs-hyperlink#2]
Hi there,

Is it possible to add a setting with a default value for the `target` attribute?

We would like to set it to `_blank` by default.

Will appreciate if we can have some quick solution for that :)

Thanks!

**Comment by trinhtam** [comment]
Okey, wait for me a few minutes.

**Comment by trinhtam** [comment]
Please update new version & update Hyperlink config:
`...
    hyperlink: {
      class: Hyperlink,
      config: {
         shortcut: 'CMD+L',
         target: '_blank', // default null
         rel: 'nofollow', // default null
      }     
    },
    ...
`

**Comment by mykhailo-monchak** [comment]
Perfect! Thank you for that!

Not urgent, but just another idea is to add an ability to show/hide `target` and `rel` controls from the settings. I'm sure not all of us need all of them together.

For example, I would go with `_blank` as the default target and both controls are hidden. My users need just place an URL, but I need the `a` to be with `_blank`

You are doing a great job!

**Comment by trinhtam** [comment]
Okey, thank for idea.
