### ISSUE TITLE
bug: pasted link is not valid

### ISSUE THREAD

**Issue by mykhailo-monchak** [trinhtam/editorjs-hyperlink#3]
it says that the link is not valid, but it is:

https://www.amazon.com/dp/006124189X?tag=aboutcom02thebalancecareers-20&linkCode=ogi&th=1&psc=1&ascsubtag=2275753|n1c710c18321742109bfab4ecc5f93e8915

**Comment by mykhailo-monchak** [comment]
the same is for 
mailto:support@gmail.com

**Comment by mykhailo-monchak** [comment]
some more wrond URLs:

- https://gsuite.google.com/intl/en_ie/products/meet/?utm_source=google&utm_medium=cpc&utm_campaign=emea-NL-all-en-dr-bkws-all-all-trial-e-googlemeet-1008069&utm_content=text-ad-none-none-DEV_c-CRE_454638492618-ADGP_Hybrid%20%7C%20AW%20SEM%20%7C%20BKWS%20~%20EXA_M:1_NL_EN_Neutral_Hangouts_V6_Meet-KWID_43700056326463546-kwd-980370380-userloc_1010543&utm_term=KW_hangouts-ST_hangouts&gclid=EAIaIQobChMI6rfR2aKs6wIVDZiyCh34hgR1EAAYASAAEgKT4PD_BwE&gclsrc=aw.ds

- https://www.simplypsychology.org/learning-kolb.html#:~:text=Kolb's

- https://www.thebalancecareers.com/active-listening-skills-with-examples-2059684#:~:text=Active

- https://www.amazon.com/Nonviolent-Communication-Language-Life-Changing-Relationships/dp/189200528X/ref=sr_1_1?crid=1RMW266JPR72V&dchild=1&keywords=non-violent+communication+by+marshall+rosenberg&qid=1597950142&sprefix=non-violent%2Caps%2C226&sr=8-1

**Comment by mykhailo-monchak** [comment]
maybe we can add a setting to disable the validation?

**Comment by trinhtam** [comment]
Sorry EditorJS doesn't support paste for inline tool.

**Comment by mykhailo-monchak** [comment]
Just to be sure that I was clear enough. When I'm editing some sort of links, the plugin is not able to save it because of an error. Please see the screenshot below:

<img width="727" alt="Screenshot 2020-11-18 at 15 49 36" src="https://user-images.githubusercontent.com/27423454/99538569-d25c0f00-29b5-11eb-9f9f-7f0d40b033e2.png">

I'm sure the reason is that the plugin validation is considering the link as incorrect, isn't it?

**Comment by trinhtam** [comment]
Okey, sorry. Please update new version
`editorjs-hyperlink@1.0.3`

**Comment by mykhailo-monchak** [comment]
thank you!
