### ISSUE TITLE
[help] duplicate link icons on inlineToolbar

### ISSUE THREAD

**Issue by orbachar** [trinhtam/editorjs-hyperlink#7]
![image](https://user-images.githubusercontent.com/57751360/101281749-8ee90980-37d9-11eb-87a7-67bd338fdac1.png)

after adding this tool, the old icon still there. how can I remove it?

**Comment by mykhailo-monchak** [comment]
Hi @orbachar 

You can configure tools that are displaying in the toolbar.
Just provide the list of needed tools in the config and do not include what you would like to skip. Like this:
`inlineToolbar: ['bold', 'italic', 'hyperlink', 'marker', 'inlineCode']`

Please find more details [here](https://editorjs.io/configuration#inline-toolbar-order)

Regards

**Comment by orbachar** [comment]
awesome! thanks!
