### ISSUE TITLE
Please update NPM package with the latest code

### ISSUE THREAD

**Issue by mykhailo-monchak** [trinhtam/editorjs-hyperlink#8]
Hi @trinhtam 

Could you please update the NPM package with the latest available code and bump the version?

Thanks,
Mikhail

**Comment by mykhailo-monchak** [comment]
Hi @trinhtam 

Could you please add me to the NPM package and the repository maintainers? Or just update the NPM package to the latest version.

Please!

**Comment by trinhtam** [comment]
Ok, editorjs-hyperlink@1.0.5 ready. Thank you

**Comment by mykhailo-monchak** [comment]
Thanks
